Repository m3ntorship/personal-resume, pull requests merged in 2020-09, with the labels that each got.

#16 global tailwind Config
  frontend/src/components/TestComponent/index.jsx
  frontend/src/css/global.css
  frontend/src/css/main.css
  frontend/src/css/tailwind.css
  frontend/tailwind.config.js
Labels: Ready for review

#20 Reusable Button component
  frontend/package.json
  frontend/src/components/TestComponent/index.jsx
  frontend/src/components/TestComponent/style.css
  frontend/src/components/shared/button/index.js
  frontend/src/css/main.css
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: Ready for review

#21 Rewiring postcss to create-react-app
  frontend/config-overrides.js
  frontend/config-webpack-postcss.js
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/css/main.css
  frontend/src/index.js
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: Approved

#25 added global styling to: body - sections - paragraphs - class:container
  frontend/src/css/global.css
Labels: Approved

#26 remove margin and block styles from reusable button component
  frontend/src/components/TestComponent/index.jsx
  frontend/src/components/shared/button/index.js
Labels: Ready for review

#18 Update README.md
  README.md
Labels: Approved

#29 Make prototype component
  frontend/src/App.js
  frontend/src/components/TestComponent/index.jsx
Labels: Approved, Ready for review

#34 Container width Adjustment
  frontend/src/css/global.css
Labels: Approved

#27 added Best expertise section
  backend/db.json
  frontend/src/App.js
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
  frontend/src/components/BestExpertiseSection/Card/gear.png
  frontend/src/components/BestExpertiseSection/Card/index.jsx
  frontend/tailwind.config.js
Labels: Ready for review

#35 Creating Estimate Section
  backend/db.json
  frontend/src/App.js
  frontend/src/components/EstimateSection/index.jsx
Labels: Approved

#36 Reusable heading
  frontend/src/App.js
  frontend/src/components/BestExpertiseSection/Card/gear.png
  frontend/src/components/TestComponent/index.jsx
  frontend/src/components/shared/button/index.js
  frontend/src/components/shared/heading/index.js
  frontend/tailwind.config.js
Labels: Approved

#45 Introduce Nestjs
  api/.eslintrc.js
  api/.prettierrc
  api/nest-cli.json
  api/package.json
  api/src/app.controller.spec.ts
  api/src/app.controller.ts
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/main.ts
  api/test/app.e2e-spec.ts
  api/test/jest-e2e.json
  api/tsconfig.build.json
  api/tsconfig.json
  api/yarn.lock
Labels: Ready for review

#44 used heading component in best expertise section
  frontend/src/App.js
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
  frontend/src/components/BestExpertiseSection/Card/index.jsx
  frontend/src/components/EstimateSection/index.jsx
Labels: Ready for review

#33 Creating About us section including progress bar component
  backend/db.json
  frontend/src/App.js
  frontend/src/components/AboutUsSection/AboutUs.jsx
  frontend/src/components/ProgressBar/ProgressBar.jsx
Labels: Ready for review

#31 Gallery component
  backend/db.json
  frontend/public/images/img-art.png
  frontend/public/images/img-battle-board-game.png
  frontend/public/images/img-black-and-white.png
  frontend/public/images/img-gray-laptop-codes.png
  frontend/public/images/img-photo-of-imac.png
  frontend/public/images/img-young-woman-thinking.png
  frontend/src/App.js
  frontend/src/components/GalleryComponent/Gallery.jsx
Labels: request changes

#38 WIP: Setup and infrastructure
  .dockerignore
  .github/workflows/playground_fullstack_dev.yaml
  .lintstagedrc
  Dockerfile.playground.backend
  Dockerfile.playground.frontend
  api/json-server-db.json
  api/package.json
  api/src/main.ts
  api/yarn.lock
  backend/package.json
  backend/yarn.lock
  deploy/commons_fullstack/00_namespace.yaml
  deploy/commons_fullstack/deployment.yaml
  deploy/commons_fullstack/service.yaml
  deploy/dev/fullstack/apply/00_namespace.yaml
  deploy/dev/fullstack/apply/deployment.yaml
  deploy/dev/fullstack/apply/ingress.yaml
  deploy/dev/fullstack/apply/service.yaml
  frontend/.env.development
  frontend/.env.production
  frontend/.gitignore
  frontend/.huskyrc
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
  frontend/src/components/EstimateSection/index.jsx
  frontend/src/modules/apis/index.js
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: Work in progress

#32 Updates Section
  api/json-server-db.json
  frontend/src/App.js
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
  frontend/src/components/EstimateSection/index.jsx
  frontend/src/components/UpdatedPosts/comment-regular.svg
  frontend/src/components/UpdatedPosts/heart-regular.svg
  frontend/src/components/UpdatedPosts/index.jsx
  yarn.lock
Labels: Approved

#54 Merge/navbar header
  frontend/src/App.js
  frontend/src/components/Header/index.jsx
  frontend/src/components/Navbar/index.jsx
Labels: Ready for review

#51 "best design quality" section
  api/json-server-db.json
  frontend/public/images/Quote.svg
  frontend/public/images/black-samsung-tablet-computer.png
  frontend/public/images/person-using-black-and-white-smartphone-and-holding-blue-card.png
  frontend/public/images/silver-imac-displaying-collage-photos.png
  frontend/src/App.js
  frontend/src/components/best-design-quality/index.jsx
Labels: Approved

#64 Move images directory
  api/json-server-db.json
  frontend/public/images/Icon.svg
  frontend/public/images/comment-regular.svg
  frontend/public/images/heart-regular.svg
  frontend/src/components/Form/contact.svg
  frontend/src/components/Navbar/Logo.png
  frontend/src/components/Navbar/index.jsx
  frontend/src/components/UpdatedPosts/index.jsx
Labels: Approved

#61 Responsive Gallery component
  api/json-server-db.json
  frontend/src/components/GalleryComponent/Gallery.jsx
Labels: Ready for review

#81 Fix/some issues
  api/json-server-db.json
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
  frontend/src/components/BestExpertiseSection/Card/index.jsx
  frontend/src/components/Footer/index.jsx
  frontend/src/components/Form/index.js
  frontend/src/components/GalleryComponent/Gallery.jsx
  frontend/src/components/Navbar/index.jsx
  frontend/src/components/UpdatedPosts/index.jsx
  frontend/tailwind.config.js
Labels: Approved

#67 responsive navbar and header
  frontend/src/components/Header/index.jsx
  frontend/src/components/Navbar/index.jsx
  frontend/tailwind.config.js
Labels: Approved

#86 Reusable Container
  frontend/src/components/EstimateSection/index.jsx
  frontend/src/components/UpdatedPosts/index.jsx
  frontend/src/components/shared/container/index.jsx
Labels: Approved

#85 responsive form and footer
  frontend/src/components/Footer/index.jsx
  frontend/src/components/Form/index.js
  frontend/src/components/shared/heading/index.js
Labels: Approved

#89 container/best-design-quality
  frontend/src/components/BestDesignQuality/index.jsx
  frontend/src/components/shared/container/index.jsx
Labels: Ready for review

#100 Use/Reusable Container with Navbar and Header
  frontend/src/components/BestDesignQuality/index.jsx
  frontend/src/components/EstimateSection/index.jsx
  frontend/src/components/Header/index.jsx
  frontend/src/components/Navbar/index.jsx
  frontend/src/components/shared/container/index.jsx
Labels: Ready for review

#99 Applying reusable container to form and footer
  frontend/src/components/Footer/index.jsx
  frontend/src/components/Form/index.js
Labels: Approved

#102 Applied reusable container to gallery section
  frontend/src/components/GalleryComponent/Gallery.jsx
Labels: Approved

#101 applied reusable container to work process section
  frontend/src/components/WorkProcessSection/index.jsx
Labels: Approved

#105 change my-12 to be 24 to consider margin collapsing at reusable container
  frontend/src/components/shared/container/index.jsx
Labels: Ready for review

#103 adding overlay layer to improve title clarity
  frontend/src/components/EstimateSection/index.jsx
Labels: Approved

#104 Apply/reuseable contaier best expertise
  frontend/src/components/BestExpertiseSection/BestExpertiseSection.jsx
Labels: Ready for review

#106 Navigation update
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/links/dto/links.dto.ts
  api/src/links/links.controller.spec.ts
  api/src/links/links.controller.ts
  api/src/links/links.module.ts
  api/src/links/links.service.ts
  api/src/main.ts
  api/src/models/links.schema.ts
  api/src/shared/http-error.filter.ts
  api/src/types/links.ts
  api/yarn.lock
Labels: Ready for review
